# Generated by Django 4.2.7 on 2025-04-17 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('phone_number', models.CharField(
                    blank=True,
                    max_length=15
                )),
                ('address_line_1', models.CharField(
                    blank=True,
                    max_length=50
                )),
                ('address_line_2', models.CharField(
                    blank=True,
                    max_length=50
                )),
                ('city', models.CharField(
                    blank=True,
                    max_length=50
                )),
                ('state', models.CharField(
                    blank=True,
                    max_length=50
                )),
                ('country', models.CharField(
                    blank=True,
                    max_length=50
                )),
                ('postal_code', models.CharField(
                    blank=True,
                    max_length=10
                )),
                ('newsletter_subscription', models.BooleanField(
                    default=False
                )),
                ('profile_picture', models.ImageField(
                    blank=True,
                    null=True,
                    upload_to=profiles.models.user_profile_picture_path
                )),
                ('created_at', models.DateTimeField(
                    auto_now_add=True
                )),
                ('updated_at', models.DateTimeField(
                    auto_now=True
                )),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),
    ]
