# Generated by Django 4.2.7 on 2025-04-20 04:25

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=community.models.achievement_image_path),
        ),
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.ImageField(upload_to=community.models.badge_image_path),
        ),
        migrations.AlterField(
            model_name='progressentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='progress_images/'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='social_posts/'),
        ),
    ]
