# Generated by Django 4.2.7 on 2025-04-20 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', 
        '0002_alter_achievement_image_alter_badge_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeRequirement',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('description', models.TextField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeReward',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('description', models.TextField()),
                ('points_value', models.IntegerField(default=0)),
                ('badge', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='community.badge'
                )),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='requirements',
            field=models.ManyToManyField(
                related_name='challenges',
                to='community.challengerequirement'
            ),
        ),
        migrations.AddField(
            model_name='challenge',
            name='rewards',
            field=models.ManyToManyField(
                related_name='challenges',
                to='community.challengereward'
            ),
        ),
    ]
