# Generated by Django 4.2.7 on 2025-04-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'accounts',
            '0002_order_orderitem_payment_remove_product_category_and_more'
        ),
    ]

    operations = [
    ]
