# Generated by Django 4.2.7 on 2025-04-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_product_id',
            field=models.CharField(
                blank=True,
                help_text='Stripe Product ID for this plan',
                max_length=100
            ),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='stripe_price_id',
            field=models.CharField(
                blank=True,
                help_text='Stripe Price ID for this plan',
                max_length=100
            ),
        ),
    ]
